(setq org-agenda-custom-commands '(("n" "Agenda and all TODO's" ((agenda "") (alltodo)))
								   ("w" "Work" tags "+work-waiting-maybe-SCHEDULED>\"<now>\"/TODO")
								   ("h" "Home" tags "-waiting-maybe-work-SCHEDULED>\"<now>\"/TODO")
								   ("c" "Couch" tags "+internet-adrianna-desktop-waiting-maybe-work-SCHEDULED>\"<now>\"/TODO")))
(setq org-agenda-include-diary t)
(setq org-agenda-ndays 1)
(setq org-agenda-skip-deadline-prewarning-if-scheduled t)
(setq org-agenda-skip-scheduled-if-done t)
(setq org-agenda-window-setup (quote current-window))
(setq org-archive-location "~/Dropbox/org/archive/%s_archive::")
(setq org-deadline-warning-days 4)
(setq org-directory "~/Dropbox/org")
(setq org-file-apps '((auto-mode . emacs)
					  ("\\.mm\\'" . default)
					  ("\\.x?html?\\'" . default)
					  ("\\.pdf\\'" . default)
					  ("\\.ppt\\'" . default)))
(setq org-habit-show-habits-only-for-today nil)
(setq org-link-abbrev-alist '(("hydra" . "https://intranet.athenahealth.com/hydra/taskview.esp?ID=")
							  ("wiki" . "https://intranet.athenahealth.com/wiki/node.esp?ID=")
							  ("hermes" . "https://intranet.athenahealth.com/hermes/queue/view.esp?JOBID=")))
(setq org-log-done (quote time))
(setq org-log-into-drawer t)
(setq org-mobile-inbox-for-pull "~/Dropbox/org/from-mobile.org")
(setq org-modules '(org-bbdb org-bibtex org-docview org-gnus org-info org-jsinfo
					org-habit org-irc org-mew org-mhe org-rmail org-vm org-wl org-w3m
					org-checklist org-learn org-registry org2rem))
(setq org-scheduled-past-days 1)

(require 'find-lisp)
(setq org-agenda-files (find-lisp-find-files "~/Dropbox/org" "\.org$"))

(require 'org)
(global-set-key "\C-cl" 'org-store-link)
(global-set-key "\C-cc" 'org-capture)
(global-set-key "\C-ca" 'org-agenda)
(global-set-key "\C-cb" 'org-iswitchb)
(setq org-mobile-directory "~/Dropbox/MobileOrg")
;(org-agenda-to-appt)

(provide 'org-customizations)
